# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f38ff333a61ae0976ef918cf9d34f17e3388354c8e7800577cc3c1d4cbbc6b86a0a3b883a3dc60c7142f2c360a447fd5028fbfe7c06f8423d142ae0055a25d4

test:
  secret_key_base: ccbad6e02b40cd5bd20840fd58dfecfc8f0e07a5df417d1a0030db9f3a7ca61a06b4422afc5cc6039e6ff8b67bd13dfbd66c8c47d5f1755ffb823ae2ccdf89f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
